# Generated by Django 3.2.13 on 2022-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
